apiVersion: batch/v1
kind: Job
metadata:
  name: api-as-source
spec:
  template:
    spec:
      containers:
      - name: api-as-source
        image: 172.30.1.1:5000/myproject/py-etl-explore
        args:
        - python
        - -m
        - commands.api_as_source
      restartPolicy: OnFailure
  backoffLimit: 2
