apiVersion: batch/v1
kind: Job
metadata:
  name: pandas-etl
spec:
  template:
    spec:
      containers:
      - name: api-as-source
        image: 172.30.1.1:5000/myproject/py-etl-explore
        command: ["python"]
        args: ["-m", "pandas_etl", "load", "--verbose"]
      restartPolicy: Never
  backoffLimit: 2
