apiVersion: batch/v1
kind: Job
metadata:
  name: bonobo-etl
spec:
  template:
    spec:
      containers:
      - name: py-etl-explore
        image: 172.30.1.1:5000/myproject/py-etl-explore
        args:
        - python
        - -m
        - commands.bonobo_etl
        - load
        - "--verbose"
      restartPolicy: OnFailure
  backoffLimit: 2
