apiVersion: batch/v1
kind: Job
metadata:
  name: api-as-source
spec:
  template:
    spec:
      containers:
      - name: api-as-source
        image: 172.30.1.1:5000/myproject/py-etl-explore
        args:
        - python
        - commands/api_as_source.py
      restartPolicy: OnFailure
  backoffLimit: 2
---
apiVersion: batch/v1
kind: Job
metadata:
  name: bonobo-etl
spec:
  template:
    spec:
      containers:
      - name: py-etl-explore
        image: 172.30.1.1:5000/myproject/py-etl-explore
        args:
        - python
        - commands/bonobo_etl.py
        - load
        - --verbose
      restartPolicy: OnFailure
  backoffLimit: 2
---
apiVersion: batch/v1
kind: Job
metadata:
  name: pandas-etl
spec:
  template:
    spec:
      containers:
      - name: api-as-source
        image: 172.30.1.1:5000/myproject/py-etl-explore
        args:
        - python
        - commands/pandas_etl.py
        - load
        - --verbose
      restartPolicy: OnFailure
  backoffLimit: 2
---
